nyc_salma:   # nom du profil (doit correspondre au projet dbt)
  target: dev             # cible par défaut
  outputs:
    dev:
      type: duckdb        # on précise qu’on utilise DuckDB
      path: data/nyc_parking_violations.db  # chemin du fichier de base de données
